### ISSUE TITLE
How can you use best meta-test acc as your experiment's result

### ISSUE THREAD

**Issue by Miaotxy** [Gorov/DiverseFewShot_Amazon#6]
![image](https://user-images.githubusercontent.com/26009601/68770796-cd0d0b80-0661-11ea-97fa-e23a0db73af9.png)

**Comment by Gorov** [comment]
Note that there is no "best meta-test acc" stored in the code. The variable "best_test_acc" stores the test acc of meta-dev tasks at this epoch. We do early-stopping with meta-dev test acc and report the corresponding meta-test test acc. 

Also please point me to the line of the code. The code, by design, should not even be able to access the meta-test set during training.

**Comment by Miaotxy** [comment]
get it, applogize for my carelessness

**Comment by Miaotxy** [comment]
One more question Please~
It seems your code meta-eval and meta-test on all the 23 * 3 tasks? 

![image](https://user-images.githubusercontent.com/26009601/68780684-9b9c3c00-0671-11ea-8363-2f20ef1d75c6.png)

**Comment by GeneZC** [comment]
@Miaotxy It seems the code is incomplete.

**Comment by Wangpeiyi9979** [comment]
I 

> get it, applogize for my carelessness



> One more question Please~
> It seems your code meta-eval and meta-test on all the 23 * 3 tasks?
> 
> ![image](https://user-images.githubusercontent.com/26009601/68780684-9b9c3c00-0671-11ea-8363-2f20ef1d75c6.png)
我看代码觉得他也是在所有23*3的task上进行测试的。。。加个微信讨论一下可以吗。。
